# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SygicConvertor
                                 A QGIS plugin
 Donne un itiniraire optimisé avec un jeu de points pour Sygic Navigation (guidage GPS)
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-10-13
        copyright            : (C) 2025 by E-SI/Sanchez Matteo
        email                : matteo.sanchez@e-si.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SygicConvertor class from file SygicConvertor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Sygic_Convertor import SygicConvertor
    return SygicConvertor(iface)
